### ISSUE TITLE
Only one authorized_keys is uploaded when booting to rescue

### ISSUE THREAD

**Issue by jooola** [ansible-collections/community.hrobot#112]
##### SUMMARY

When activating the rescue system for a Robot server, only a single SSH key is uploaded to the rescue system `/root/.ssh/authorized_keys`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.hrobot.boot`

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.5]
  config file = None
  configured module search path = ['/home/jo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/pipx/venvs/ansible-core/lib/python3.11/site-packages/ansible
  ansible collection location = /home/jo/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/opt/pipx/venvs/ansible-core/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection                               Version
---------------------------------------- -------
community.general                        9.0.1  
community.hrobot                         2.0.0  
community.library_inventory_filtering_v1 1.0.1 
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Boot to rescue
  hosts: all
  gather_facts: false

  vars:
    # SSH keys to add to the server. Must already exist in Robot.
    authorized_keys:
      - 21:ea:a3:5c:02:a6:0c:42:0b:ef:b5:60:ae:5b:07:9b # key1
      - fa:7d:44:f4:d2:bc:52:96:52:6f:b1:12:19:6b:48:38 # key2
      - fc:3c:b4:42:c9:bf:f9:6e:be:58:d3:12:40:c7:13:b2 # key3

  module_defaults:
    group/community.hrobot.robot:
      hetzner_user: "{{ lookup('ansible.builtin.env', 'ROBOT_USER') }}"
      hetzner_password: "{{ lookup('ansible.builtin.env', 'ROBOT_PASSWORD') }}"

  tasks:
    - name: Enable rescue system
      delegate_to: localhost
      community.hrobot.boot:
        server_number: "{{ server_number }}"
        rescue:
          authorized_keys: "{{ authorized_keys }}"
          os: linux

    - name: Reboot into rescue system
      delegate_to: localhost
      community.hrobot.reset:
        server_number: "{{ server_number }}"
        reset_type: hardware

    # Might already fail here, if the authorized key used to connect was not uploaded
    - name: Wait for the server to be reachable
      ansible.builtin.wait_for_connection:
        delay: 5

- name: Check
  hosts: all
  gather_facts: true
  tasks:
    - name: Check all auth orized_keys are uploaded
      ansible.builtin.shell:
        cmd: test $(wc -l /root/.ssh/authorized_keys) == 3
```

##### EXPECTED RESULTS

The 3 ssh keys to be present in the `/root/ssh/.authorized_keys` files.

##### ACTUAL RESULTS

Only one key is present in the `/root/ssh/.authorized_keys` files.
