### ISSUE TITLE
hrobot.firewall: Request failed: 400 INVALID_INPUT (invalid input)

### ISSUE THREAD

**Issue by ThomasTr** [ansible-collections/community.hrobot#88]
##### SUMMARY
Previous working firewall rules throws error: Request failed: 400 INVALID_INPUT (invalid input)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hrobot.firewall

##### ANSIBLE VERSION

```
ansible [core 2.15.5]
  config file = /Users/xxx/Projects/infrastructure/ansible/hrobot/ansible.cfg
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.5.0_1/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] (/opt/homebrew/Cellar/ansible/8.5.0_1/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /Users/xxx/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.hrobot 1.8.1  

# /opt/homebrew/Cellar/ansible/8.5.0_1/libexec/lib/python3.11/site-packages/ansible_collections
Collection       Version
---------------- -------
community.hrobot 1.8.1  
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Even dead simple firewall config throws error

```
- name: Configure hrobot firewall - ensure both ssh ports open
  community.hrobot.firewall:
    hetzner_user: ""
    hetzner_password: ""
    server_ip: "{{ ansible_host }}"
    state: present
    allowlist_hos: yes
    rules:
      input:
        - name: Allow ICMP protocol, so you can ping your server
          ip_version: ipv4
          protocol: icmp
          action: accept
      output:
        - name: Accept everything
          action: accept
  delegate_to: localhost
```

##### ACTUAL RESULTS

```paste below

```

**Comment by felixfontein** [comment]
Hmm, I tried slightly different firewall configs, and they worked fine:
```
    - community.hrobot.firewall:
        hetzner_user: "{{ hetzner_user }}"
        hetzner_password: "{{ hetzner_pass }}"
        server_ip: "{{ server_ip }}"
        # server_number: "{{ server_no }}"
        port: main
        state: present
        filter_ipv6: false
        allowlist_hos: true
        rules:
          input:
            # - name: "Allow ICMP"
            #   ip_version: "ipv4"
            #   protocol: icmp
            #   action: "accept"
            - name: "Allow all"
              ip_version: "ipv4"
              action: "accept"
          output:
            - name: "Allow all"
              action: "accept"
```
I tried this both with `server_number` and `server_ip` (both worked fine), and with the ICMP rule commented in and out.
